#!/usr/bin/env python3
"""Parses a spec file and extracts all build dependencies"""

import sys

builddeps = set()

for specfile in sys.argv:
    with open(specfile, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith('BuildRequires:'):
                _, values = line.split(':', 1)
                for value in values.split(','):
                    value = value.strip()
                    name = value.split(' ')[0] # ignore version
                    builddeps.add(name)

for name in sorted(builddeps):
    print(name)
