---
name: 'Run tests'

on:
  push:
  pull_request:
  # Disabled, because Github appears to disable the whole workflow if you have a schedule
  # and no updates for 60 days...
  #  schedule:
  #- cron: '0 7 * * *'

jobs:
  tests:
    name: Run tests
    # on a ubuntu-20.04 VM
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./demo/
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: recursive
      - run: ./test-templating.sh
        working-directory: ./templating
      - run: ./tests/test_versioning.sh
        working-directory: .
      - run: ./prepare.sh
      - run: ./builder/build.sh -B MYCOOLARG=iLikeTests sdist
      - run: ./builder/build.sh -B MYCOOLARG=iLikeTests rocky-9
      # Again, now very fast due to the layer cache 
      - run: ./builder/build.sh -B MYCOOLARG=iLikeTests rocky-9
      # Three cache builds:
      # - First one will write the vendor cache
      - run: ./builder/build.sh -c -B MYCOOLARG=iLikeTests rocky-9
      # - Second one will use the vendor cache, but the Docker layer cache gets invalidated by the new cache file
      - run: ./builder/build.sh -c -B MYCOOLARG=iLikeTests rocky-9
      # - Third one is very fast due to the Docker layer cache
      - run: ./builder/build.sh -c -B MYCOOLARG=iLikeTests rocky-9
      # Do a reproducible rocky-8 build (does not work for centos-7)
      - run: ../tests/test-rocky-8-reproducible.sh
      - run: ../tests/test-rocky-9-reproducible.sh
